outdir: outputs/evaluation/repair_fundps_poisson_rough_weight10000
name: fm4pde_poisson_rough_first100
dataset: poisson
data_path: __set_by_launcher__
data_offset: 0
resolution: 128
max_size: 100
batch_size: 1
pkl_path: __required__
rbf_scale: 0.05
seed: 0
init_latents: rbf
iterations: 500
sigma_min: 0.01
sigma_max: 10
rho: 7
observation:
- type: sparse
  loss_type: mse
  known_indices:
  - 500
  - 500
  normalize: true
- type: pde
  loss_type: huber
  derivative_method: finite_diff
guidance:
  type: dps
  weights:
  - 0
  - 10000
  - 0
n_plots: 0
n_process_steps: 2
wandb: false
