outdir: /data1/zjinzxf2025/C01Python/DiffusionPDE/outputs/ddis_comparison_20260919/evaluation/ddis/poisson/id
name: fm4pde_poisson_id_first100
task: inverse
dataset: poisson
data_path: /data1/zjinzxf2025/C01Python/DiffusionPDE/outputs/ddis_comparison_20260919/data/preprocessing/id/data/DiffPDE/poisson_test_hf
data_offset: 0
resolution: 128
max_size: 100
batch_size: 1
pkl_path: __required__
rbf_scale: 0.05
surrogate_path: __required__
surrogate_config:
  n_modes:
  - 64
  - 64
  in_channels: 1
  out_channels: 1
  hidden_channels: 64
  n_layers: 4
seed: 0
init_latents: rbf
iterations: 500
sigma_min: 0.002
sigma_max: 80
rho: 7
observation:
- type: sparse
  loss_type: l1
  known_indices:
  - 500
  - 500
  normalize: true
guidance:
  type: daps_multires
  surrogate_type: fno_pad
  sigma_min_1: 0.005
  sigma_max_2: 5
  init_resolution: 64
  upsampling_mode: bilinear
  upsampling_step: 50
  annealing:
    num_steps: 100
    sigma_max: 10
    sigma_min: 0.01
    sigma_final: 0
    rho: 7
  diffusion:
    num_steps: 5
    sigma_min: 0.001
    sigma_final: 0
    rho: 7
  langevin:
    num_steps: 20
    lr: 0.0001
    lr_min_ratio: 0.01
    lr_rho: 1
    eta: 0.1
    tau: 0.001
    weights:
    - 0
    - 20
    weights_1:
    - 0
    - 10
    weights_2:
    - 0
    - 15
    dynamic_control: false
    decay_type: linear
    decay_rate: 1.5
    min_steps: 3
    dynamic_lr: false
    lr_schedule: sigmoid
    lr_decay_rate: 0.5
    lr_warmup_steps: 0
n_plots: 0
n_process_steps: 2
plot_spectral_energy: true
wandb: false
