outdir: exps
name: ''
dataset: darcy
data_path: /data1/zjinzxf2025/C01Python/DiffusionPDE/outputs/ddis_comparison_20260919/data/preprocessing/rough/data/DiffPDE/darcy_test_hf
data_offset: 0
resolution: 128
max_size: 100
batch_size: 1
pkl_path: __required__
rbf_scale: 0.05
seed: 0
init_latents: rbf
iterations: 500
sigma_min: 0.002
sigma_max: 80
rho: 7
observation:
- type: sparse
  loss_type: mse
  known_indices:
  - 500
  - 500
  normalize: true
- type: pde
  loss_type: huber
  derivative_method: finite_diff
guidance:
  type: dps
  weights:
  - 0
  - 50000
  - 0
n_plots: 0
n_process_steps: 2
wandb: false
